#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.
#
# description: Redis is an in memory key-value store database
#
### BEGIN INIT INFO
# Provides: redissentinel_sentinel_sentinel
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: redissentinel_sentinel_sentinel init script
### END INIT INFO

SENTINELNAME=sentinel
EXEC="su -s /bin/sh -c '/usr/local/bin/redis-server /etc/redis/${SENTINELNAME}.conf --sentinel' redis"
CLIEXEC=/usr/local/bin/redis-cli


PIDFILE=/var/run/redis/${SENTINELNAME}.pid

if [ ! -d /var/run/redis ]; then
    mkdir -p /var/run/redis
    chown redis /var/run/redis
fi

case "$1" in
    status)
        if [ -f $PIDFILE ]
        then
          echo "$SENTINELNAME $PIDFILE exists, pid is $(cat $PIDFILE), should be running"
          exit 0
        else
          echo "redis$SENTINELNAME $PIDFILE doesn't exist"
          exit 3
        fi
        ;;
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting Redis server..."
                eval $EXEC
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."

                kill ${PID}

                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for Redis to shutdown ..."
                    sleep 1
                done
                echo "Redis stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
